# ------------------------------------------------------------
# Hook0 Cloud Build Pipeline
# Builds and pushes API, Frontend, and Output-Worker in parallel
# ------------------------------------------------------------

steps:

  # Ensure Dockerfiles use modern BuildKit syntax
  - name: gcr.io/cloud-builders/gcloud
    id: enable-buildkit
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔧 Enabling BuildKit syntax headers if missing..."
        for f in ./api/Dockerfile ./frontend/Dockerfile ./output-worker/Dockerfile; do
          grep -q "syntax=docker/dockerfile" "$f" || sed -i '1i# syntax=docker/dockerfile:1.7' "$f"
        done

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:v2.0.0 || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:v2.0.0 || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:v2.0.0 || exit 0']
    
  # Build API image
  - name: gcr.io/cloud-builders/docker
    id: build-api
    args:
      [
        "build",
        "--file=./api/Dockerfile",
        "--tag=${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:$TAG_NAME",
        "--cache-from", "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:v2.0.0",
        "--build-arg=FEATURES=reqwest-rustls-tls-webpki-roots,application-secret-compatibility",
        "."
      ]
    waitFor: ["-"]

  # Tag API image as latest
  - name: gcr.io/cloud-builders/docker
    id: tag-api-latest
    args: ['tag', '${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:$TAG_NAME', '${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:latest']
    waitFor: ['build-api']

  # Build Frontend image
  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    env:
      - _ENV_API_ENDPOINT=${_ENV_API_ENDPOINT}
    args:
      [
        "build",
        "--file=./frontend/Dockerfile",
        "--tag=${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:$TAG_NAME",
        "--build-arg=API_ENDPOINT=$_ENV_API_ENDPOINT/api/v1",
        "--cache-from", "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:v2.0.0",
        "."
      ]
    waitFor: ["-"]

  # Tag Frontend image as latest
  - name: gcr.io/cloud-builders/docker
    id: tag-frontend-latest
    args: ['tag', '${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:$TAG_NAME', '${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:latest']
    waitFor: ['build-frontend']

  # Build Output-Worker image
  - name: gcr.io/cloud-builders/docker
    id: build-worker
    args:
      [
        "build",
        "--file=./output-worker/Dockerfile",
        "--tag=${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:$TAG_NAME",
        "--cache-from", "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:v2.0.0",
        "."
      ]
    waitFor: ["-"]

  # Tag Output-Worker image as latest
  - name: gcr.io/cloud-builders/docker
    id: tag-worker-latest
    args: ['tag', '${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:$TAG_NAME', '${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:latest']
    waitFor: ['build-worker']

# ------------------------------------------------------------
# Record built images for Cloud Build UI visibility
# ------------------------------------------------------------
images:
  - "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:$TAG_NAME"
  - "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_API}:latest"
  - "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:$TAG_NAME"
  - "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:latest"
  - "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:$TAG_NAME"
  - "${_REGISTRY}/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:latest"

# ------------------------------------------------------------
# Substitutions (custom variables)
# ------------------------------------------------------------
substitutions:
  _REGISTRY: "asia.gcr.io"
  _DEPLOYMENT_API: hook0-api
  _DEPLOYMENT_FRONTEND: hook0-frontend
  _DEPLOYMENT_OUTPUTWORKER: hook0-outputworker
  _ENV_API_ENDPOINT: "https://api.hook0.devenvphu.men"

# ------------------------------------------------------------
# Global options
# ------------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1