# ------------------------------------------------------------
# Hook0 Cloud Build Pipeline
# Builds and pushes API, Frontend, and Output-Worker in parallel
# ------------------------------------------------------------

steps:

  # Ensure Dockerfiles use modern BuildKit syntax
  # - name: gcr.io/cloud-builders/gcloud
  #   id: enable-buildkit
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       echo "🔧 Enabling BuildKit syntax headers if missing..."
  #       for f in ./api/Dockerfile ./frontend/Dockerfile ./output-worker/Dockerfile; do
  #         grep -q "syntax=docker/dockerfile" "$f" || sed -i '1i# syntax=docker/dockerfile:1.7' "$f"
  #       done

  # Build API image
  - name: gcr.io/cloud-builders/docker
    id: build-api
    args:
      [
        "build",
        "--file=./api/Dockerfile",
        "--tag=asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_API}:$TAG_NAME",
        "--build-arg=FEATURES=reqwest-rustls-tls-webpki-roots,application-secret-compatibility",
        "."
      ]
    waitFor: ["-"]

  # Build Frontend image
  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    env:
      - _ENV_API_ENDPOINT=${_ENV_API_ENDPOINT}
    args:
      [
        "build",
        "--file=./frontend/Dockerfile",
        "--tag=asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:$TAG_NAME",
        "--build-arg=API_ENDPOINT=$_ENV_API_ENDPOINT/api/v1",
        "."
      ]
    waitFor: ["-"]

  # Build Output-Worker image
  - name: gcr.io/cloud-builders/docker
    id: build-worker
    args:
      [
        "build",
        "--file=./output-worker/Dockerfile",
        "--tag=asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:$TAG_NAME",
        "."
      ]
    waitFor: ["-"]

# ------------------------------------------------------------
# Record built images for Cloud Build UI visibility
# ------------------------------------------------------------
images:
  - "asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_API}:$TAG_NAME"
  - "asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_FRONTEND}:$TAG_NAME"
  - "asia.gcr.io/$PROJECT_ID/${_DEPLOYMENT_OUTPUTWORKER}:$TAG_NAME"

# ------------------------------------------------------------
# Substitutions (custom variables)
# ------------------------------------------------------------
substitutions:
  _DEPLOYMENT_API: hook0-api
  _DEPLOYMENT_FRONTEND: hook0-frontend
  _DEPLOYMENT_OUTPUTWORKER: hook0-outputworker
  _ENV_API_ENDPOINT: "https://api.hook0.devenvphu.men"

# ------------------------------------------------------------
# Global options
# ------------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1